---
- name: Create a partition of 40GB for Docker and install Docker
  hosts: docker_swarm_manager, docker_swarm_worker
  become: true
  tasks:
    - name: Make sure Docker daemon starts automatically at system startup
      service:
        name: docker
        state: started
        enabled: true
  roles:
    - ansible-role-partition
    - ansible-role-docker

- name: Securely expose the Docker Daemon REST APIs
  hosts: docker_swarm_manager, docker_swarm_worker
  roles:
    - role: ansible-role-docker-remote-api
      docker_remote_client_use_certs_as_default: true
      docker_remote_server_force_deploy: true
      docker_remote_client_become: true
      docker_remote_certs_server_additional_subjects:
        - "DNS:{{ ansible_hostname }}"
        - "IP:{{ ip }}"

- name: Set up a Docker Swarm on VMs
  hosts: docker_swarm_manager, docker_swarm_worker
  become: true
  roles:
    - ansible-dockerswarm
  vars:
    docker_swarm_interface: "eth1"
