---
galaxy_info:
  author: Matteo Moratello
  description: Create a partition of 40GB for Docker
  company: Moratello

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: centos
      versions:
        - 8

  galaxy_tags: []

dependencies: []
